language: python

services: docker

python:
  - "3.6"

install: pip install tox

script:
  - tox

deploy:

    # Deploy to PyPI
  - provider: script
    script: deploy/pypi.sh
    on:
      branch: master

  - provider: script
    script: deploy/pypi_dev.sh
    on:
      branch: develop